seanbruno/qemu-bsd-user

bsd-user/mips/target_arch_cpu.c
bsd-user/mips/target_arch_signal.h
bsd-user/mips64/target_arch_cpu.c
bsd-user/mips64/target_arch_signal.h

FreeBSD kernel accepts full pointer to the allocated TLS block
through sysarch(SET_TLS) and returns that same pointer through
sysarch(GET_TLS), but in simulated rdwhr instructions it
returns the pointer offset by 0x7000 + TLS_TCB_SIZE as expected
by TLS users in userland.

Implement same thread pointer semantics as in FreeBSD kernel.

---

bsd-user/mips/target_arch_cpu.c
bsd-user/mips/target_arch_signal.h
bsd-user/mips64/target_arch_cpu.c
bsd-user/mips64/target_arch_signal.h

Reverts seanbruno/qemu-bsd-user#9
Nope this as we are going to break the ABI in head for MIPS/MIPS64 instead.  This will be fixed by a newer version of the jail and does not require changes to qemu.

Revert "Implement same thread pointer semantics as in FreeBSD kernel."

---

bsd-user/bsd-file.h
bsd-user/syscall.c

Intercept readlink(2) to return actual command, not the path to QEMU itself.
Note this solves very special cases, e.g., OpenJDK8 build with Poudriere.

Add a hack to work around a procfs(5) issue.

---

bsd-user/freebsd/os-sys.c

```
/wrkdirs/usr/ports/emulators/qemu-user-static/work/qemu-bsd-user-182181a/bsd-user/freebsd/os-sys.c: In function 'sysctl_oldcvt':
/wrkdirs/usr/ports/emulators/qemu-user-static/work/qemu-bsd-user-182181a/bsd-user/freebsd/os-sys.c:656: error: 'for' loop initial declaration used outside C99 mode
/wrkdirs/usr/ports/emulators/qemu-user-static/work/qemu-bsd-user-182181a/rules.mak:57: recipe for target 'bsd-user/freebsd/os-sys.o' failed
```
Declare `i` outside the for loop to make it build with base GCC.

os-sys: Fix build on FreeBSD 9.

---

bsd-user/bsd-file.h

It fixes PR 208952
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208952

Fix arguments for renameat

---

include/qemu/atomic.h

QEMU's atomic header defines a few macros which conflict with standard C++ function names, namely `atomic_fetch_{add,sub,and,or}`.  Disable these macros when compiling for C++.
See also: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209590
Signed-off-by: Dimitry Andric <dimitry@andric.com>

Disable atomic macros which conflict with C++

---

bsd-user/bsd-file.h

Note it is mostly cosmetic change because `unlock_user()` is no-op at the moment.

Clean up locking/unlocking path names

---

bsd-user/freebsd/os-time.h

Poudriere doesn’t work with qemu-bsd-user in 10.3, because 10.3’s pkg(8) requires utimensat() to work but os-time.h thinks it’s only available in 11.0. Qemu is returning ENOSYS, so pkg aborts.
There's probably a cleaner way of doing this #if macro.

Allow utimensat() syscall on FreeBSD 10.3, where pkg(8) requires it.

---

include/qemu/atomic.h

Reverts seanbruno/qemu-bsd-user#21
This is being replaced by a far simpler change to header file inclusion that will be available on the bsd-user branch first and then appear in upstream QEMU and this projects master branch.

Revert "Disable atomic macros which conflict with C++"

---

bsd-user/freebsd/os-time.h

I'm seeing this error message:
/usr/local/bin/ghc
kevent: failed (Bad address)
here is the syscall trace (nevents and *eventlist are both 0):
kevent(8,-347058624,1,0,0,-347058648) = -1 errno=14 (Bad address)

Don't try to copy the eventlist if the number of events is 0

---

bsd-user/main.c

If emulated program starts new thread first and
then do fork(), then qemu fails with SISEGV.
This issue can be observed in python scons or Waf.

Fix typo in  fork_end() in bsd-user/main.c.

---

bsd-user/bsd-proc.c
bsd-user/freebsd/os-proc.h
bsd-user/qemu-bsd.h
bsd-user/syscall.c
bsd-user/syscall_defs.h

not sure whether the convention for 64-bit types is to use abi_llong or a direct int64_t (I picked abi_llong).

rlim_t is an int64_t, not an abi_ulong.  fixes getrlimit/setrlimit

---

bsd-user/freebsd/os-time.h

This fixes high CPU usage within gmake when using -j

Don't overwite pselect's return value when copying out fdsets.

---

bsd-user/bsd-file.h
bsd-user/freebsd/strace.list
bsd-user/freebsd/syscall_nr.h
bsd-user/syscall.c

This removes annoying noise, i.e., `qemu: unsupported syscall: 550 (calling anyway)`.

Implement fdatasync(2) for FreeBSD.

---

bsd-user/mips/target_arch_cpu.h

FreeBSD-mips is softfloat, so don't permit qemu to execute instructions that
real hardware can't.

Disable the FPU for both 32-bit mips targets.

---

bsd-user/bsd-file.h
bsd-user/freebsd/os-stat.h

Properly decorate FreeBSD 11 compatibility function, these are
exported from libc.so.7 as versioned symbols.

Fix non-static build.

---

bsd-user/mmap.c

Also added include for sys/param.h to have __FreeBSD_version.
When I tried adding just the MAP_GUARD changes to the emulators/qemu-user-static port as a patch it only worked with the include.
I put MAP_PREFAULT commented out in the MAP_GUARD validation since it is not in mman.h.
I don't know if it is not there intentionally or just missed.

Changes to check for fd != -1 instead of !(flags & MAP_ANONYMOUS) in mmap

---

bsd-user/aarch64/target_arch_cpu.h
bsd-user/arm/target_arch_cpu.h
bsd-user/i386/target_arch_cpu.h
bsd-user/mips/target_arch_cpu.h
bsd-user/mips64/target_arch_cpu.h
bsd-user/ppc/target_arch_cpu.h
bsd-user/sparc/target_arch_cpu.h
bsd-user/sparc64/target_arch_cpu.h
bsd-user/x86_64/target_arch_cpu.h

From linux-user fdbc2b5722f6092e47181a947c90fd4bdcc1c121
tcg: Add EXCP_ATOMIC
When we cannot emulate an atomic operation within a parallel
context, this exception allows us to stop the world and try
again in a serial context.
Reviewed-by: Emilio G. Cota <cota@braap.org>
Reviewed-by: Alex Bennée <alex.bennee@linaro.org>
Signed-off-by: Richard Henderson <rth@twiddle.net>

Add missing parts for bsd-user

---

bsd-user/signal.c

but SA_SIGINFO is missing in some cases.
This can cause unexpected interrupted syscalls.
Set SA_SIGINFO earlier.
From linux-user.

To update the host kernel signal state we want to use sa_sigaction

---

bsd-user/main.c

These locks are taken in different order in accel/tcg/cpu-exec.c and in bsd-user/mmap.c. which leads to livelock visible mainly in automoc4.

Fix lock order reversion for mmap and tb locks. 

---

bsd-user/freebsd/os-thread.c
bsd-user/freebsd/os-thread.h
bsd-user/qemu.h
bsd-user/syscall_defs.h

- implement UMTX_OP_SHM mutex operation.
- log UMTX_OP_ROBUST_LISTS as not yet implemented.
This fixes autoconf test 'checking if Berkeley DB supports shared environments',  used e.g. in mail/bogofilter

Support/log more operations for user mode mutexes.

---

bsd-user/freebsd/os-socket.c
bsd-user/syscall_defs.h

- return right pointer from TARGET_CMSG_NXTHDR()
- in recvmsg(), add  support for SCM_TIMESTAMP control message
- in sendmsg(), timestamp control message have SCM_TIMESTAMP type, not SO_TIMESTAMP
This fixes:
- runaway processes found in sysutils/bareos-client
- 'Host cmsg overflow' message reported for ping a.b.c.d

sendmsg()/recvmsg() fixes.

---

bsd-user/freebsd/os-socket.h

It fixes devel/arpc and lang/erlang

No need to check msg_controllen: msg_controllen can have the value 0 and the kernel discards negative value
